<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    
    <!-- アプリケーション情報 & バージョン規約 (1.0.0.0) -->
    <Title>WoodStream PLAZA</Title>
    <Product>WoodStream PLAZA Desktop Client</Product>
    <Description>WoodStream PLAZA クライアント アプリケーション</Description>
    <Company>WoodStream Networks Tomokazu Kizawa</Company>
    <Copyright>Copyright © 2026 WoodStream Networks Tomokazu Kizawa. All rights reserved.</Copyright>
    <Version>1.0.0.1</Version>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
    
    <!-- アプリアイコン -->
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

</Project>
